import { Alias } from './alias.interface';
import { ArtworkBaseRecord } from './artwork-base-record.interface';
import { AwardBaseRecord } from './award-base-record.interface';
import { Character } from './character.interface';
import { Companies } from './companies.interface';
import { ContentRating } from './content-rating.interface';
import { GenreBaseRecord } from './genre-base-record.interface';
import { Inspiration } from './inspiration.interface';
import { ListBaseRecord } from './list-base-record.interface';
import { ProductionCountry } from './production-country.interface';
import { Release } from './release.interface';
import { RemoteID } from './remote-id.interface';
import { Status } from './status.interface';
import { StudioBaseRecord } from './studio-base-record.interface';
import { TagOption } from './tag-option.interface';
import { Trailer } from './trailer.interface';
import { TranslationExtended } from './translation-extended.interface';

export interface MovieExtendedRecord {
  aliases?: Alias[];
  artworks?: ArtworkBaseRecord[];
  audioLanguages?: string[];
  awards?: AwardBaseRecord[];
  boxOffice?: string;
  boxOfficeUS?: string;
  budget?: string;
  characters?: Character[];
  companies?: Companies;
  contentRatings?: ContentRating[];
  first_release?: Release;
  genres?: GenreBaseRecord[];
  id?: number;
  image?: string;
  inspirations?: Inspiration[];
  lastUpdated?: string;
  lists?: ListBaseRecord[];
  name?: string;
  nameTranslations?: string[];
  originalCountry?: string;
  originalLanguage?: string;
  overviewTranslations?: string[];
  production_countries?: ProductionCountry[];
  releases?: Release[];
  remoteIds?: RemoteID[];
  runtime?: number | null;
  score?: number;
  slug?: string;
  spoken_languages?: string[];
  status?: Status;
  studios?: StudioBaseRecord[];
  subtitleLanguages?: string[];
  tagOptions?: TagOption[];
  trailers?: Trailer[];
  translations?: TranslationExtended;
  year?: string;
}
