import { Alias } from './alias.interface';
import { ArtworkExtendedRecord } from './artwork-extended-record.interface';
import { Character } from './character.interface';
import { Company } from './company.interface';
import { ContentRating } from './content-rating.interface';
import { EpisodeBaseRecord } from './episode-base-record.interface';
import { GenreBaseRecord } from './genre-base-record.interface';
import { RemoteID } from './remote-id.interface';
import { SeasonBaseRecord } from './season-base-record.interface';
import { SeasonType } from './season-type.interface';
import { SeriesAirsDays } from './series-airs-days.interface';
import { SeriesCompany } from './series-company.interface';
import { Status } from './status.interface';
import { TagOption } from './tag-option.interface';
import { Trailer } from './trailer.interface';
import { TranslationExtended } from './translation-extended.interface';

export interface SeriesExtendedRecord {
  abbreviation?: string;
  airsDays?: SeriesAirsDays;
  airsTime?: string;
  aliases?: Alias[];
  artworks?: ArtworkExtendedRecord[];
  averageRuntime?: number | null;
  characters?: Character[];
  contentRatings?: ContentRating[];
  country?: string;
  defaultSeasonType?: number;
  episodes?: EpisodeBaseRecord[];
  firstAired?: string;
  lists?: unknown;
  genres?: GenreBaseRecord[];
  id?: number;
  image?: string;
  isOrderRandomized?: boolean;
  lastAired?: string;
  lastUpdated?: string;
  name?: string;
  nameTranslations?: string[];
  companies?: SeriesCompany[];
  nextAired?: string;
  originalCountry?: string;
  originalLanguage?: string;
  originalNetwork?: Company;
  overview?: string;
  latestNetwork?: Company;
  overviewTranslations?: string[];
  remoteIds?: RemoteID[];
  score?: number;
  seasons?: SeasonBaseRecord[];
  seasonTypes?: SeasonType[];
  slug?: string;
  status?: Status;
  tags?: TagOption[];
  trailers?: Trailer[];
  translations?: TranslationExtended;
  year?: string;
}
