export const PORT = 3000;
export const ADDRESS = '0.0.0.0';
export const DATABASE_URL = '';
export const DOCUMENT_TITLE = 'KamPlex API'
export const DOCUMENT_DESCRIPTION = 'REST API media streaming'
export const DOCUMENT_VERSION = '0.0.1'
export const DOCUMENT_AUTHOR = 'Kaigonia'
export const DOCUMENT_GITHUB = 'https://github.com/ktt45678'
export const DOCUMENT_EMAIL = 'ktt45678@gmail.com'