name: 'Azure Deployment'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install npm packages and build
        run: |
          npm install --also=dev
          npm run build
          npm prune --production
      - name: Deploy to Azure (kamplex-api-b1)
        uses: azure/webapps-deploy@v2
        with:
          app-name: kamplex-api-b1
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}