name: 'Azure Deployment'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'npm'
      - name: Install npm packages and build
        run: |
          npm install --include=dev
          npm run build
          rm -rf node_modules
      - name: Zip artifact
        run: zip kamplex-api.zip ./* -r
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: kamplex-api
          path: kamplex-api.zip
  deploy-a1:
    name: Deploy to Azure (A1)
    runs-on: ubuntu-latest
    if: false # Disable it
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: kamplex-api
      - name: Deploy (kamplex-api-a1)
        uses: azure/webapps-deploy@v3
        with:
          app-name: kamplex-api-a1
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_A1 }}
          package: kamplex-api.zip
  deploy-b2:
    name: Deploy to Azure (B2)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: kamplex-api
      - name: Deploy (kamplex-api-b2)
        uses: azure/webapps-deploy@v3
        with:
          app-name: kamplex-api-b2
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_B2 }}
          package: kamplex-api.zip
