name: 'Heroku Deploy'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Build
        run: |
          npm install --also=dev
          npm run build:prod
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'kamplex'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: 'https://kamplex.herokuapp.com'
          checkstring: 'Hello World!'
          rollbackonhealthcheckfailed: true
          procfile: 'web: npm run start:prod'
