name: 'Instance Deployment'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  INSTANCE_DEPLOYMENT_CONFIG: ${{ secrets.INSTANCE_DEPLOYMENT_CONFIG }}

jobs:
  env:
    name: Configure environment
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      INSTANCE_CONFIG: ${{ env.INSTANCE_CONFIG }}
    steps:
      - name: Read instance deployment config
        run: |
          if [ ! -x "$(command -v jq)" ]; then
            echo "jq not found, installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          fi
          echo "${{ env.INSTANCE_DEPLOYMENT_CONFIG }}" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done

      - name: Done
        run: echo "Done reading env"
  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: env
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'npm'
      - name: Install npm packages and build
        run: |
          npm install --include=dev
          npm run build
      - name: Zip artifact
        run: zip kamplex-api.zip ./* -r
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: kamplex-api
          path: kamplex-api.zip
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: kamplex-api
      - name: Deploy to Instance
        env:
            INSTANCE_IP: ${{ env.instanceIp }}
            INSTANCE_USER: ${{ env.instanceUser }}
            SSH_PRIVATE_KEY: ${{ env.instanceSSHPrivateKey }}
            PUBLISH_FOLDER: ${{ env.instancePublishFolder }}
            CONFIGURATION_FILE: ${{ env.instanceConfigurationFile }}
            PACKAGE_FOLDER: kamplex-api
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./* $INSTANCE_USER@$INSTANCE_IP:$PUBLISH_FOLDER
          ssh -o StrictHostKeyChecking=no -i private_key $INSTANCE_USER@$INSTANCE_IP "cd $PUBLISH_FOLDER && pm2 stop $CONFIGURATION_FILE"
          ssh -o StrictHostKeyChecking=no -i private_key $INSTANCE_USER@$INSTANCE_IP "cd $PUBLISH_FOLDER && rm -rf $PACKAGE_FOLDER && unzip kamplex-api.zip -d $PACKAGE_FOLDER && rm kamplex-api.zip"
          ssh -o StrictHostKeyChecking=no -i private_key $INSTANCE_USER@$INSTANCE_IP "cd $PUBLISH_FOLDER && cd $PACKAGE_FOLDER && npm install"
          ssh -o StrictHostKeyChecking=no -i private_key $INSTANCE_USER@$INSTANCE_IP "cd $PUBLISH_FOLDER && pm2 start $CONFIGURATION_FILE"
          echo "Successfully deployed to selected Instance."
